# Metadata about this component, to be used in the CMS
spec:
  structures:
    - profile_topper
  label: "Topper - Profile Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading:
    - text: Heading
      style:
  subheading: Subheading.
  styles:
    section:
      background_c: bg-wvu-gold
      text_c: text-wvu-blue

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: