baseURL: 'https://dscomponents.wvu.edu'
languageCode: 'en-us'
title: 'Bookshop Components'
timeZone: America/New_York
staticDir: assets

disableKinds:
  - taxonomy
  - term

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  hugoVersion:
    extended: true
    min: 0.125
  imports:
    - path: github.com/wvuweb/wvu-ds-v3-hugo
    - path: components.local
    - path: github.com/cloudcannon/bookshop/hugo/v3
    - path: github.com/adamglenn/wvu-ds-v3-bookshop-components
      mounts:
      - source: component-library
        target: layouts/partials/bookshop/
      - source: component-library
        target: assets/bookshop/
  replacements:
    - components.local -> ../component-library
    - github.com/wvuweb/wvu-ds-v3-hugo -> ../../wvu-ds-v3-hugo/
    - github.com/adamglenn/wvu-ds-v3-bookshop-components -> ../../wvu-ds-v3-bookshop-components/