# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "YouTube Shorts"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Shorts
  shorts:
    - title:
      video_id:
      ratio: 9x16

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: