# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero"
  description:
  icon: crown
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _bookshop_name: design-system/topper/hero
  topper_type: hero
  label:
  background_image:
  alt_text:
  heading:
    - text:
      highlight:
  subheading: Subheading.
  body_text:
  styles:
    vibe: down-to-business
    color_palette:
    enable_blend: false
    enable_pattern: false
    tint_opacity: 0.5
    margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  body_text:
    type: textarea