# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading:
    - text: Heading
      style:
  subheading: Subheading.
  vibe: down_to_business
  background_c: bg-dark text-white
  heading_c:
  background_layers:
    img_blend_mode:
    img_opacity:
    pattern: 
    pattern_c: bg-white
    pattern_opacity: 0.2
    tint_opacity: 0.7
    texture: false
  styles:
    section: bg-wvu-accent--blue text-white py-6
    container: 
    superheading: h3 wvu-shout wvu-text-letter-spacing-lg
    heading: display-4 oliviar-black text-uppercase
    subheading: helvetica-neue-light h2

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: