# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
    - content_blocks
  label: "Topper - Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: hero-topper
  label: ""
  background_image: ""
  alt_text: ""
  heading:
    - text: Heading
      highlight: ""
  subheading: Subheading.
  body_text: ""
  styles:
    vibe: down_to_business
    color_palette: wvu_blue
    enable_blend: false
    enable_pattern: false
    tint_opacity: 0.5
    margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  body_text:
    type: textarea