# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading:
    - text: Heading
      style:
  subheading: Subheading.
  background_c: bg-dark text-white
  heading_c:
  vibe: down_to_business
  enable_pattern: true
  enable_blend: false
  background_layers:
    img_blend_mode:
    img_opacity:
    pattern_c: bg-white
    pattern_opacity: 0.1
    tint_opacity: 0.7

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: