# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Columns 2-1-1"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  column_a: [bookshop:structure:column_blocks]
  column_b: [bookshop:structure:column_blocks_sm]
  column_c: [bookshop:structure:column_blocks_sm]
  config:
    edit_mode_only: false
  layout:
  styles:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
