# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Big Search"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    background_image:
    alt_text:
    heading:
    lead:
    body:
    postscript:
    postscript_links:
  config:
    is_main: false
    id:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: