# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Contact Us"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  address: []
  phone:
  fax:
  email:
  contacts:
    - contact:
  config:
    edit_mode_only: false
    is_main: true
    section_id: directory

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
