# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Default"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    - text: Heading
  subheading: Subheading.
  vibe: down_to_business
  background_c: bg-light text-wvu-blue
  heading_c:
  background_layers:
    img_blend_mode:
    img_opacity: .4
    pattern: 
    pattern_c: bg-white
    pattern_opacity: .2
    tint_opacity:
    texture: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: