# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
  label: "Student Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  student:
  super_heading:
    label:
    text:
  heading:
  subheading:
  config:
    edit_mode_only: false
    hide_collection_pages: true
  styles:
    typography: wvu_experience

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
