# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button Group"
  description:
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  body:
    - Lede.
    - Body.
  buttons:
    - text: Call to Action
      url:
      icon: 
  postscript:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  postscript:
    type: markdown