# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - place_blocks
  label: "Alternating Grid"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  subheading:
  items:
    - heading:
      image:
      text:
      ctas:
  postscript:
    text:
    postscript_links:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: