# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero w/Icons"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading: Heading
  subheading: Subheading.
  items:
    - icon: book
      text: Text
      url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: